# Block Transfer <blocktransfer.io>

NO_INCOME_CLAIMS = "We approximated the ~0.5% difference between brokerage and
direct-registered investment portfolios for an equally-weighted all-cap equity
portfolio at a leading broker with 12 diversified security purchases per month.
This figure does not accord for systematic devaluations of securities due to
excess sales of nonexistent shares, remarkably higher spreads for derivatives,
expense ratios for baskets of shares that could be acquired en mass individually
given efficient bulk trading functionality, improper tax classifications of cash
in lieu of dividends, or lack of portfolio cash or securities interest income."

MARKETING_THUMBNAIL = "We use a chart showing the growth of $1,000 invested per
month for 40 years at 9% and 9.5% returns to showcase the impact of this
'small' difference, inter alia. The base return in question is an average
return before inflation for investments in equally-weighted all-cap American
index funds. Past performance does not guarantee future results. We make no
claim that your investments will attain average market returns, appreciate in
value whatsoever, or grow at a rate faster than comperable investments at a
traditional broker. Investing involves risk including complete loss of capital.
These figures are meant to show the affect hidden spreads can have on a 
theoretical portfolio. They are used for informational purposes only."
