# Block Transfer <blocktransfer.io>

RECORD_DATE = "We take record of all investors at the first ledger to close
at or after 0:00:00 UTC on a split record date, if opted for by an issuer."

PAYMENT_DATE = "We freeze all asset activity the day before a split becomes
effective at 6PM Eastern (22:00:00 UTC). During the next two hours, we effect
the split. We unfreeze accounts the day the split is effective beginning at
00:00:00 UTC (not to exceed 2:00:00 UTC) or 8PM Eastern (10PM Eastern). As such,
there exist at least two hours on the day before a split is 'effective' in New
York time during which investors can transfer their post-split balances."

STATEMENT = "We find these operations in accordance with Rule 17Ad-15 since,
inter alia, the account freeze in question (i) does not last longer than three business days, (ii) affects all investors essentially equally, and (iii)
notifies investors immediately of transfer requests rejected because of frozen
split processing."

HISTORY = "Past split records are avaliable in this folder's parent directroy:
*docs
  _compliance
    _this doc_
  _assets
    _all assets_
      asset.toml
	    [splits]
"
