# Block Transfer <blocktransfer.io>

# todo: merge this with micr & banking data -> DynamoDB 
# todo: impliment federation addrs with sort key?

[GC5TUPFLOXCINDYHQVYYLLVYP6GKHT65ELB2Q2WLFTGN63YYIXPQTDFJ]
accredited_soft = true
accredited_verified = true
accredited_expiration = "2027-11-23"
active = true
affiliations = { DEMO = "current" }
backup_witholding = false
bad_actor = false
dealer = false
qib = false
show_506b = ["TEST"]
reg_A2_max = "10000.11"
reg_CF_max = "5000.44"
state = "GA"
type = "individual"
underwriter = false
