# Block Transfer <blocktransfer.io>
# US Patent 17/396,742

# In accordance with ยง240.15c2-11, BlockTrans Syndicate is the transfer agent for the issuers of securities detailed here.
# The Stellar distributed network, Stellar Development Foundation, and affiliates thereof are not associated such issuers.

VERSION = "2.5.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
FEDERATION_SERVER = "https://stellarid.io/federation"
ACCOUNTS = [
"GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7",
"GAQKSRI4E5643UUUMJT4RWCZVLY25TBNZXDME4WLRIF5IPOLTLV7N4N6",
"GD2OUJ4QKAPESM2NVGREBZTLFJYMLPCGSUHZVRMTQMF5T34UODVHPRCY",
"GDTCN6C4BUWRQMB7IAPXZKSBQKA22LY4I6YVBHHYCOKZCIBRRTUWCEDE"
] # Issuer, distributor, treasury, DWAC

[DOCUMENTATION]
ORG_NAME = "BlockTrans Syndicate"
ORG_DBA = "Block Transfer"
ORG_URL = "https://www.blocktransfer.io"
ORG_LOGO = "https://blocktransfer.io/logo.png"
ORG_DESCRIPTION = "Digital assets for global capital markets"
ORG_PHYSICAL_ADDRESS = "99 Wall Street #4640, New York, NY 10005"
ORG_PHONE_NUMBER = "+1 (844) 42-STOCK"
ORG_GITHUB = "blocktransfer"
ORG_OFFICIAL_EMAIL = "inquiries@blocktransfer.io"
ORG_SUPPORT_EMAIL = "support@blocktransfer.io"
ORG_LICENSING_AUTHORITY = "U.S. Securities and Exchange Commission"
ORG_LICENSE_TYPE = "CIK"
ORG_LICENSE_NUMBER = "0001846058"

[[PRINCIPALS]]
name = "John F. Wooten, IV"
email = "john@blocktransfer.io"
github = "JFWooten4"
id_photo_hash = "0dce43292a7dd2c6ef021cca9f84330ceeec34e8587172453bc2b05f1bd13edd"
verification_photo_hash = "a3b5109c1afb0d7ce22780fc5a656bda0f24b63d4bbddcff35f44f0b8e62ff48"

[[CURRENCIES]]
attestation_of_reserve = "https://blocktransfer.io/assets/bt-dollar/latest.pdf"
anchor_asset = "USD"
anchor_asset_type = "fiat"
code = "BTD"
conditions = "Block Transfer is not a bank and does not itself take deposits. You will not receive any interest, credit, or other earnings on the funds in your Block Transfer account."
display_decimals = 7
desc = "You can deposit funds as an unsecured claim against Block Transfer, a Deleware corporation regulated by the SEC. We hold deposits in fungible bulk, matched 1:1 on and off Stellar. Your funds are not insured by the FDIC or SIPC, but we do maintain various error and ommission policies with a Berkshire Hathaway company."
image = "https://blocktransfer.io/imgs/btd.png"
issuer = "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
is_unlimited = true
is_asset_anchored = true
name = "BT Dollars"
redemption_instructions = "Use our app to link your bank."
status = "test"

[[CURRENCIES]]
attestation_of_reserve = "https://blocktransfer.io/assets/DEMO.toml"
anchor_asset = "Reg D"
anchor_asset_type = "stock"
code = "DEMO"
code_template = "DEMO????????"
conditions = "Fully paid and non-assessable shares."
display_decimals = 7
desc = "Example Company is used interally for product demos and development." # General solicitation disclaimer for 506B here
image = "https://blocktransfer.io/imgs/demo.png"
issuer = "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
is_unlimited = true
is_asset_anchored = true
name = "Example Security"
redemption_instructions = "This company is not public, so you can only hold shares here on its books"
# "($75 fee) Send your shares to cede*blocktransfer.io and initiate a request from your legacy broker."
status = "test"
